name: PlatformIO CI

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-platformio-
    
    - name: Run PlatformIO Compiler
      run: platformio run
      working-directory: source

    - name: Find Firmware
      id: find_firmware
      run: |
        FIRMWARE_PATH=$(find source/.pio -name "*.bin" | head -n 1)
        if [ -z "$FIRMWARE_PATH" ]; then
          echo "No firmware file found!"
          exit 1
        fi
        echo "firmware_path=$FIRMWARE_PATH" >> "$GITHUB_OUTPUT"
        echo "Firmware found at: $FIRMWARE_PATH"
      
    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: ${{ steps.find_firmware.outputs.firmware_path }}
        if-no-files-found: error

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.sha }}
        release_name: Prerelease ${{ github.sha }}
        draft: false
        prerelease: true

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.find_firmware.outputs.firmware_path }}
        asset_name: firmware.bin
        asset_content_type: application/octet-stream