name: 🚀 PsychOS CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'source/**'
      - 'platformio.ini'
  pull_request:
    paths:
      - 'source/**'
      - 'platformio.ini'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate Tag Availability
      id: check_tag
      run: |
        VERSION="0.4.11-beta"
        if git rev-parse "v$VERSION" >/dev/null 2>&1; then
          echo "::error::Tag v$VERSION already exists!"
          exit 1
        fi
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio-${{ hashFiles('source/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-platformio-

    - name: Build Firmware
      run: platformio run
      working-directory: source
      env:
        PLATFORMIO_FORCE_COLOR: true

    - name: Locate Firmware
      id: find_firmware
      run: |
        set -e
        # Specific path to firmware binary (adjust based on your platformio.ini environment)
        FIRMWARE_PATH=$(find source/.pio/build -name 'firmware*.bin' -not -name '*bootloader*' -type f -print -quit)

        if [ -z "$FIRMWARE_PATH" ]; then
          echo "::error::Firmware binary not found in build artifacts!"
          exit 1
        fi

        FIRMWARE_NAME="psychos-${{ steps.check_tag.outputs.version }}.bin"
        mv "$FIRMWARE_PATH" "$FIRMWARE_NAME"
        echo "firmware_path=$FIRMWARE_NAME" >> "$GITHUB_OUTPUT"
        echo "firmware_name=$FIRMWARE_NAME" >> "$GITHUB_OUTPUT"
        echo "Found firmware: $FIRMWARE_NAME"

    - name: Generate Release Notes
      id: release_notes
      run: |
        cat << EOF > RELEASE.md
        ## 🎉 PsychOS Alpha Release v${{ steps.check_tag.outputs.version }}

        ### ✨ New Features
        - USB HID Communication Bridge
        - Volume Control System
          - Smooth increment/decrement with direction lock
          - Configurable polling rate (1000Hz)
        - FreeRTOS Task Management

        ### 📥 Installation
        Download \`${{ steps.find_firmware.outputs.firmware_name }}\` and flash using:
        \`\`\`bash
        # Windows
        esptool.py --chip esp32s3 --port COM[X] write_flash 0x0 ${{ steps.find_firmware.outputs.firmware_name }}
        
        # Linux/macOS
        esptool.py --chip esp32s3 --port /dev/ttyUSB0 write_flash 0x0 ${{ steps.find_firmware.outputs.firmware_name }}
        \`\`\`

        ### ⚠️ Known Issues
        - Matrix scanning in development
        - Configuration system pending

        ### 🛠️ Next Steps
        - Complete matrix scanning implementation
        - Add configuration interface
        - Implement layer system
        EOF

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.check_tag.outputs.version }}
        name: PsychOS v${{ steps.check_tag.outputs.version }}
        body_path: RELEASE.md
        prerelease: true
        files: |
          ${{ steps.find_firmware.outputs.firmware_path }}
