name: PlatformIO CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/source/.platformio
        key: ${{ runner.os }}-platformio-${{ hashFiles('source/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-platformio-
    
    - name: Run PlatformIO
      run: platformio run
      working-directory: source

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: source/.pio/build/**/firmware.bin

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: source/.pio/build/**/firmware.bin
        asset_name: firmware.bin
        asset_content_type: application/octet-stream
        token: ${{ secrets.GITHUB_TOKEN }}